ktor:
    application:
        modules:
            - com.ippon.vluce.application.ApplicationKt.module
    deployment:
        port: 8080
    mongodb:
        uri: "mongodb+srv://Cluster92613:uP1bRLTiNZFwYqLJ@clustervlu.vxjrghe.mongodb.net"
